### ISSUE TITLE
Missing or invalid example.yaml location file

### ISSUE THREAD

**Issue by daljaz** [plume-design/opensync-fut-base#3]
When following instructions in the [repository_structure.md](https://github.com/plume-design/opensync-fut-base/blob/master/doc/repository_structure.md) file, you are instructed to copy the [fut_location_example.yaml](https://github.com/plume-design/opensync-fut-base/blob/master/config/fut_location_example.yaml) file into the `config/locations/` directory with the filename `example.yaml`. The `example.yaml` file is loaded when using the `pset` tool which should load the location file for your selected testbed. A warning prints that looks like this:
```
(DOCKER:fut-extra)osync@osync-docker:~/qa/fut-base$ (=) pset opensync_testbed
Traceback (most recent call last):
  File "/home/osync/qa/lib_testbed/generic/tools/reserve", line 213, in <module>
    main(sys.argv)
  File "/home/osync/qa/lib_testbed/generic/tools/reserve", line 119, in main
    reslib = ReserveTool(args, ReserveTool.get_config('example'))
  File "/home/osync/qa/lib_testbed/generic/tools/reserve", line 66, in get_config
    tb_config = config.load_tb_config(tb_path, skip_deployment=True)
  File "/home/osync/qa/lib_testbed/generic/util/config.py", line 382, in load_tb_config
    attach_capabilities_cfg_to_nodes(config)
  File "/home/osync/qa/lib_testbed/generic/util/config.py", line 235, in attach_capabilities_cfg_to_nodes
    capab = get_model_capabilities(node["model"])
  File "/home/osync/qa/lib_testbed/generic/util/config.py", line 599, in get_model_capabilities
    raise Exception(f"Cannot find model properties file for {model}. Make sure {cap_file} exists")
Exception: Cannot find model properties file for <device_model,_example_pp203x>. Make sure /home/osync/qa/config/model_properties/reference/<device_model,_example_pp203x>.yaml exists
```

**Comment by daljaz** [comment]
The environment is set correctly and you are able to proceed with test execution. The warning message can be ignored.

If you wish to remove the warning message, populate the `example.yaml` file with valid values, like the ones used for the selected testbed. After that no warning prints.
