### ISSUE TITLE
FUT testing interrupted: 16 errors during collection.

### ISSUE THREAD

**Issue by liquan0828** [plume-design/opensync-fut-base#4]
Hi @daljaz 
 
This is LockeLi from Sagemcom R&D team.
There are some errors block the FUT testing when I run 'pytest test/ -v' command.
Jeremy Wu asked me to report issues directly to github for the FUT team.
I uploaded some files that maybe need for you. Could you please help to fix it ? 
Thanks

**Error log as below:**
[example]root@plume-server-docker:/home/plume/qa/fut-base$ **pytest test/ -v**
================================================= test session starts ==================================================
platform linux -- Python 3.10.9, pytest-7.4.2, pluggy-1.3.0 -- /opt/.pyenv/versions/3.10.9/bin/python
cachedir: .pytest_cache
rootdir: /home/plume/qa/fut-base
configfile: pytest.ini
plugins: select-0.1.2, ordering-0.6, cov-3.0.0, dependency-0.5.1, anyio-4.0.0, xdist-2.5.0, forked-1.6.0, allure-pytest-2.13.2, repeat-0.9.1, timeout-2.1.0, rerunfailures-10.3, qase-pytest-5.0.2
timeout: 480.0s
timeout method: signal
timeout func_only: False
collected 0 items / 16 errors                                                                                          
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/opt/.pyenv/versions/3.10.9/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/_pytest/config/__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/_pytest/main.py", line 306, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
    outcome.get_result()
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/y/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/plume/qa/fut-base/test/conftest.py", line 74, in pytest_sessionfinish
    server = pytest.server
  File "/opt/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pytest/__init__.py", line 171, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module pytest has no attribute server
[example]root@plume-server-docker:/home/plume/qa/fut-base$

**Comment by daljaz** [comment]
@liquan0828 it is not possible to determine directly what is the cause of your issue just from the provided logs. When you see this error, the server handler did not instantiate correctly during the fut_setup stage. One of the possible causes is incorrectly modifying your source code, for example the test case configuration generator input files. I would suggest that you attempt to execute the same on unmodified sources first to get a baseline.

**Comment by liquan0828** [comment]
Dear @daljaz 

GW/Leaf1/Leaf2: PP203X

The source code download from:
            _fut-base [repository: https://github.com/plume-design/opensync-fut-base]
                ├── lib_testbed -> ../lib_testbed
                └── config
                    └── locations -> ../../config/locations
                    └── model_properties -> ../../config/model_properties
            config
                └── locations
                └── model_properties
                    └── reference [repository: https://github.com/plume-design/opensync-qa-dut-config]
            lib_testbed
                └── generic [repository: https://github.com/plume-design/opensync-qa-lib-testbed]_

We did not change the source code, but use the default test scripts for PP203X.
Do we need to create new testcases with generator?
The errors occured on collection stage.
**pytest test/ -v**    &   **pytest --collect-only**
This two commands have the same error.
**Log:** 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Please give some suggestions for us. Thanks a lot.

Regards
